config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "restaurants#index"
  resources :reviews
  resources :restaurants do
    collection do
      get 'restaurant_search'
      get 'tag_search'
      get 'area_search'
    end
  end

  resources :users do
    member do
      get 'restaurant_show'
    end
  end

  get '/tags/:id' => 'tags#show', as: 'tag'
  get '/categories' =>'categories#index'

end



# resourcesは以下の意味と同じ。restfulな設計を心がける（あんまうまく行ってないけど）。
# GET    'restaurants'     => 'restaurants#index'
# GET    'restaurants/:id' => 'restaurants#show'
# GET    'restaurants/new' => 'restaurants#new'
# POST   'restaurants'     => 'restaurants#create'
# GET    'restaurants/:id/edit' => 'restaurants#edit'
# DELETE 'restaurants/:id' => 'restaurants#destroy'
# PUT    'restaurants/:id' => 'restaurants#update'

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tags
  has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :tags
  belongs_to :user
  has_many :reviews

  validates :name, presence: true
  validates :area, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :restaurants
  belongs_to :category
  has_and_belongs_to_many :reviews
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :restaurants
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_out_path_for(resource)
    user_session_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_filter :authenticate_user!, only: :new


  def index
    @restaurants = Restaurant.all
    @areas = Restaurant.group(:area).order('count_area desc').count('area').keys.compact
    @categories = Category.all
    @tag_group1 = Tag.where(id: 1..3)
    @tag_group2 =Tag.where(id: 4..5)
    @tag_group3 =Tag.where(id: 6..7)
    @tag_group4 =Tag.where(id: 8..9)
    @tag_group5 =Tag.where(id: 10..11)
    @fake = Restaurant.new
  end

  def new
    @restaurant = Restaurant.new
    @categories = Category.all
  end

  def create
    if Restaurant.where(:name => info_params.values[0])
      redirect_to action: "new", notice: '既に同じレストランが存在しています！' and return
    end
    @restaurant = Restaurant.where(:name => info_params.values[0]).first_or_initialize(info_params)
    @restaurant.user_id = current_user.id
    if params[:tag_children]
      params[:tag_children].keys.each do |tag_child|
        @restaurant.tags << Tag.find_by(:name => "#{tag_child}")
      end
    end

    if @restaurant.save
      redirect_to action: "index" and return
    else
      redirect_to action: "new", notice: 'レストラン名とエリアを入力して下さい！！' and return
    end

  end

  def restaurant_search
    @restaurants = Restaurant.where("name LIKE(?)", "%#{key_info[:restaurant]}%")
  end

  def tag_search
    if params[:tag_children]
      names = params[:tag_children].keys
      @restaurants = Tag.find_by(name: names[0]).restaurants
      names.each do |tag_child|
        tag = Tag.find_by(name: tag_child)
        @restaurants = @restaurants.includes(:tags).where(restaurants_tags: {restaurant_id: tag.restaurant_ids}).references(:tags)
      end

      # @restaurants = Tag.where(name: names).map { |i| i.restaurants}.flatten
      # @restaurants = names.map { |tag_child| Tag.find_by(name: "#{tag_child}").restaurants }.flatten これはうえの1文と全く同じものをとってきている！
    end
  end

  def area_search
    @restaurants = Restaurant.where(area: params[:params_area])
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @user = @restaurant.user
    @reviews = @restaurant.reviews
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    @tags = @restaurant.tags
    @categories = Category.all
  end

  def update
    restaurant = Restaurant.find(params[:id])
    if restaurant.user_id == current_user.id
    restaurant.update(name: params[:name], price: params[:price], review: params[:review])
    restaurant.tags = Tag.where(:name => params[:tag_children].keys)
    restaurant.save
    end
  end

  def destroy
    restaurant = Restaurant.find(params[:id])
    restaurant.destroy
    redirect_to action: :index
  end

  private
   def info_params
    params.require(:restaurant).permit(:name, :price, :tag_list, :area, :review)
   end

   def key_info
    params.permit(:restaurant)
   end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @categories = Category.all
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @review = Review.new(basic_params)
    tag_names = params[:tag_children].keys
    tag_names.each do |tag_name|
      tag = Tag.find_by(:name => "#{tag_name}")
      @review.tags << tag
    end
    @review.save
    redirect_to controller: :restaurants, action: :index
  end

  def edit
    @review = Review.find(params[:id])
    @tags = @review.tags
    @categories = Category.all
  end

  def update
    review = Review.find(params[:id])
    @restaurant = Restaurant.find(review.restaurant_id)
    if review.user_id == current_user.id
    review.update(price: params[:price], review: params[:review])
    review.tags = Tag.where(:name => params[:tag_children].keys)
    review.save
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to controller: :restaurants, action: :index
  end

  private
  def basic_params
    params.require(:review).permit(:price, :review, :restaurant_id, :user_id)
  end



end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    tag = Tag.find(params[:id])
    @restaurants = Restaurant.tagged_with("#{tag.name}")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @restaurants = User.find(params[:id]).restaurants
    render :partial => 'restaurant'
  end

  def restaurant_show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <%= category.name %>
  <br>
  <% tags = category.tags %>
    <% tags.each do |tag| %>
      <%= tag.name %>
    <% end %>
  <br><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sitlog4" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Sitlog4</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">

              <li>
                <button type="button" class="btn btn-link">
                  <%= link_to "トップへ", root_path %>
                </button>
              </li>

            <% if user_signed_in? %>
              <li>
                <button type="button" class="btn btn-link">
                <%= link_to "マイページへ", "/users/#{current_user.id}" %>
                </button>
              </li>
            <% end %>

            <li>
              <button type="button" class="btn btn-link">
              <% if user_signed_in? %>
                  <%= link_to "ログアウトする", destroy_user_session_path, method: :delete %>
              <% else %>
                  <%= link_to "ログインする", user_session_path, method: :post %>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <%= link_to "新規登録する",  new_user_registration_path %>
              <% end %>
              </button>
            </li>

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">

          <%= yield %>
        </div>
        <div class="col-lg-3">
 <!--          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div> -->
      </div>

      <footer>
<!--         <p>&copy; Company 2015</p> -->
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/restaurants/area_search.html.erb
<h1>検索結果</h1>
<h4>(This is just a first-review. If you want further information, keep going!!!）</h4>
<% @restaurants.each do |restaurant| %>
<%= link_to restaurant.name, "#{restaurant.id}" %>
<br>
タグ：<% restaurant.tags.each do |tag|  %> <%= tag.name %>,<% end %>
<br>
単価：<%= restaurant.price %>
<br>
レビュー：<%= restaurant.review %>
<br><br>
<% end %>

app/views/restaurants/edit.html.erb
  <%= form_tag("/restaurants/#{@restaurant.id}", :method => :patch) do %>
    <h3>
      編集する
    </h3>
    <input value="<%= @restaurant.name %>" name="name" autofocus="true">
    <input value="<%= @restaurant.price %>" name="price">
  <div>
    <p>これまでのタグ一覧　クリックすると追加されます。</p>
      <% @categories.each do |category| %>
        <%= category.name %><br>
        <% tags = category.tags %>
          <% tags.each do |tag| %>
            <% if @tags.include?(tag) %>
              <%= check_box "tag_children", "#{tag.name}", {:checked => true}, true, false %><%= tag.name %> <!-- 第一引数：パラメータ、第二引数：表示名 -->
            <% else %>
              <%= check_box "tag_children", "#{tag.name}", {:checked => false}, true, false %><%= tag.name %>
            <% end %>
          <% end %>
          <br><br>
      <% end %>
  </div>
    <input value="<%= @restaurant.area %>" name="area">
    <input style="height:140px; width:200px;" align ="bottom" value="<%= @restaurant.review %>" name="review" ></textarea>
    <input type="submit" value="編集を確定する">
  <% end %>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">

    <button type="button" class="btn btn-primary btn-lg btn-block">
      <a href="/restaurants/new" style ="color: gold;">クリックしてお店のレビューを投稿しよう！</a>
    </button>


    <br><br><br>
    <%= form_tag({action: :tag_search}, {method: :get}) do %>
        <%= Category.find(1).name %>
        <br>
        人数を１つ選択して下さい：
        <% @tag_group1.each do |tag| %>
          <%= check_box "tag_children", "#{tag.name}", {}, true, false %><%= tag.name %>
      <% end %>
        <br>
        気分を１つ選択して下さい：
        <% @tag_group2.each do |tag| %>
          <%= check_box "tag_children", "#{tag.name}", {}, true, false %><%= tag.name %>
        <% end %>
        <br><br><br>
        <%= Category.find(2).name %>
        <br>
        スピード感を１つ選択して下さい：
        <% @tag_group3.each do |tag| %>
          <%= check_box "tag_children", "#{tag.name}", {}, true, false %><%= tag.name %>
      <% end %>
        <br>
        気分で１つ選択して下さい：
        <% @tag_group4.each do |tag| %>
          <%= check_box "tag_children", "#{tag.name}", {}, true, false %><%= tag.name %>
      <% end %>
        <br><br><br>
        <%= Category.find(3).name %>
        <br>
        相手のことを考えながら決めて下さい：
        <% @tag_group5.each do |tag| %>
          <%= check_box "tag_children", "#{tag.name}", {}, true, false %><%= tag.name %>
      <% end %>
        <br><br>
        <button type="button" class="btn btn-primary btn-lg btn-block">
          <input type="submit" value="この条件で検索する" style="color: gold; background-color: green;">
        </button>
    <% end %>


<!-- ここからレストラン -->

    <br>
    <div class="col-sm-6" >
      <div style="background-color: yellow;">
      <%= form_for :restaurant, :url => {:action => "restaurant_search"}, method: :get do |f|%>
        <br>
        <p>レストラン名から検索する</p>
        <input class="search__query" name="restaurant" placeholder="レストラン名で検索" type="text"></input>
      <% end %>
      </div>
    </div>

    <!-- ここからエリア -->
    <div class="col-sm-6" >
      <div style="background-color: silver;">
          <%= form_tag({action: :area_search}, {method: :get}) do %>
            <p>エリアから検索する</p>
            <input class="search__query" name="area" placeholder="エリアで検索" type="text">  </input>
          <% end %>

            <p>クリックするとそのエリアのレストラン一覧へ飛びます</p>
            <% @areas.each do |area| %>
              <button type="button" class="btn btn-link">
                <%= link_to area, area_search_restaurants_path(params_area: :"#{area}") %>
              </button>
            <% end %>
        </div>
    </div>

  </div>
</div>

app/views/restaurants/new.html.erb
<div style="color: red;">
<%= params[:notice] %>
</div>


<%= form_for(@restaurant) do |f| %>
  <%= f.text_field :name, placeholder: :"レストラン名" %>
  <%= f.text_field :area, placeholder: :"エリアを入力して下さい" %>


  <div>
      <p>タグ一覧　クリックすると追加されます。</p>
        <% @categories.each do |category| %>
          <%= category.name %><br>
          <% tags = category.tags %>
            <% tags.each do |tag| %>
              <%= check_box "tag_children", "#{tag.name}", {}, true, false %><%= tag.name %>
            <!-- 第一引数：パラメータ、第二引数：表示名 -->
            <% end %>
            <br><br>
        <% end %>
    </div>
  <%= f.text_field :price, placeholder: :"客単価" %>
  <%= f.text_area :review, placeholder: :"自由記述" %>
  <%= f.submit "投稿する"  %>
<% end %>

<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
<script>
  $(function(){
    $(".tags_btn").click(function () {
      $(this).css("background-color", "red");
    });
  });
</script> -->

app/views/restaurants/restaurant_search.html.erb
<h1>検索結果</h1>
<h4>(This is just a first-review. If you want further information, keep going!!!）</h4>
<% @restaurants.each do |restaurant| %>
<%= link_to restaurant.name, "#{restaurant.id}" %>
<br>
タグ：<% restaurant.tags.each do |tag|  %> <%= tag.name %>,<% end %>
<br>
単価：<%= restaurant.price %>
<br>
レビュー：<%= restaurant.review %>
<br><br>
<% end %>

app/views/restaurants/show.html.erb
<!-- ここから最初の投稿（restaurantsテーブルより） -->
<h4>店名：<%= @restaurant.name %></h4><h4>価格：<%= @restaurant.price %></h4><h4>エリア：<%= @restaurant.area %></h4>
<p><%= link_to "このレストランにレビューを加える", new_review_path(:id => "#{@restaurant.id}") %></p>
----------------------------------------------------------
<h5>投稿者: <%= link_to @user.nickname, user_path(:id => "#{@user.id}") %></h5>

<h5>レビュー：<%= @restaurant.review %></h5>

<h5>タグ：<%= @restaurant.tags.pluck(:name).join(",") %></h5>
<% if user_signed_in? && current_user.id == @restaurant.user_id %>
<h4><%= link_to "編集する", edit_restaurant_path %></h4>
<h4><%= link_to "削除する", "/restaurants/#{@restaurant.id}", method: :delete %></h4>
<% end %><br>


<!--ここから2つ目以降の投稿（reviewsテーブルより） -->
<% @reviews.each do|review| %>
  <h5>投稿者: <%= link_to review.user.nickname, user_path(:id => "#{@user.id}") %></h5>
  <h5>レビュー：<%= review.review %></h5>
  <h5>タグ：<%= review.tags.map{|i| i.name}.join(",") %></h5>

  <% if user_signed_in? && current_user.id == review.user_id %>
  <h4><%= link_to "編集する", edit_review_path(:id => review.id) %></h4>
  <h4><%= link_to "削除する", "/reviews/#{review.id}", method: :delete %></h4>
  <% end %><br>
<% end %>

app/views/restaurants/tag_search.html.erb
<h4>クリックしてお店情報をcheck!!</h4>
<% if @restaurants %>
  <div>
    <% @restaurants.each do |restaurant| %>
      店名：<%= link_to restaurant.name, "/restaurants/#{restaurant.id}" %><br>
      エリア：<%= restaurant.area %><br>
      価格：<%= restaurant.price %><br>----------------<br>
    <% end %>
  </div>

<% else %>
  <div>
    ちゃんとパラメータを送りたまへ（あとでjqueryでalert画面とか表示しよう）
  </div>
<% end %>

app/views/restaurants/update.html.erb
<div class="success">
  <h3>
    更新が完了しました。
  </h3>
  <a class="btn" href="/">投稿一覧へ戻る</a>
</div>

app/views/reviews/edit.html.erb
  <%= form_tag("/reviews/#{@review.id}", :method => :patch) do %>
    <h3>
      編集する
    </h3>

  <div>
    <p>これまでのタグ一覧　クリックすると追加されます。</p>
      <% @categories.each do |category| %>
        <%= category.name %><br>
        <% tags = category.tags %>
          <% tags.each do |tag| %>
            <% if @tags.include?(tag) %>
              <%= check_box "tag_children", "#{tag.name}", {:checked => true}, true, false %><%= tag.name %> <!-- 第一引数：パラメータ、第二引数：表示名 -->
            <% else %>
              <%= check_box "tag_children", "#{tag.name}", {:checked => false}, true, false %><%= tag.name %>
            <% end %>
          <% end %>
          <br><br>
      <% end %>
  </div>
    <input style="height:140px; width:200px;" align ="bottom" value="<%= @review.review %>" name="review" ></textarea>
    <input type="submit" value="編集を確定する">
  <% end %>

app/views/reviews/new.html.erb
<h4><%= @restaurant.name %></h4>
<h4><%= @restaurant.area %></h4>
----------------------------------
<%= form_for(@review) do |f| %>
  <div>
    <p>これまでのタグ一覧　クリックすると追加されます。</p>
      <% @categories.each do |category| %>
        <%= category.name %><br>
        <% tags = category.tags %>
          <% tags.each do |tag| %>
            <%= check_box "tag_children", "#{tag.name}", {}, true, false %><%= tag.name %>
          <!-- 第一引数：パラメータ、第二引数：表示名 -->
          <% end %>
          <br><br>
      <% end %>
  </div>
  <%= f.text_field :price, placeholder: :"客単価" %>
  <%= f.text_area :review, placeholder: :"自由記述" %>
  <%= f.hidden_field :restaurant_id, :value => @restaurant.id %>
  <%= f.hidden_field :user_id, :value => current_user.id  %>
  <%= f.submit "投稿する"  %>
<% end %>

app/views/reviews/update.html.erb
<div class="success">
  <h3>
    更新が完了しました。
  </h3>
  <a class="btn" href="/restaurants/">投稿一覧へ戻る</a>
  <a class="btn" href="/restaurants/<%= @restaurant.id %>">お店のページに戻る</a>
</div>

app/views/tags/show.html.erb
<% @restaurants.each do |restaurant| %>
<%= link_to restaurant.name, "/restaurants/#{restaurant.id}" %>
<br>
タグ：<%= restaurant.tags  %>
<br>
単価：<%= restaurant.price %>
<br>
レビュー：<%= restaurant.review %>
<br><br>
<% end %>

app/views/users/_restaurant.html.erb
<% @restaurants.each do |restaurant| %>
<h4><%= restaurant.name %></h4>
<%= restaurant.review %><br><%= restaurant.area %><br>
<% id = restaurant.id %>
<%= link_to "この投稿の詳細へ", "/users/#{id}/restaurant_show" %>
<br><br>
<% end %>

app/views/users/restaurant_show.html.erb
<h4>店名：<%= @restaurant.name %></h4>
<h4>価格：<%= @restaurant.price %></h4>
<h4>エリア：<%= @restaurant.area %></h4>
<h4>レビュー：<%= @restaurant.review %></h4>
<h4>タグ：<%= @restaurant.tags.pluck(:name).join(",") %></h4>


<% if user_signed_in? && current_user.id == @restaurant.user_id %>
<h4><%= link_to "編集する", edit_restaurant_path %></h4>
<h4><%= link_to "削除する", "/restaurants/#{@restaurant.id}", method: :delete %></h4>
<% end %>

app/views/users/show.html.erb
<div class="contents row">
<%= render @restaurants %>
</div>